[package]
name = "file_logger"
version = "0.4.3"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]
edition = "2018"
description = "A logger that outputs all messages to a file."


[dependencies]
chrono = "0.4.6"
log = { version = "0.4.6", features = ["std"] }
